In [ ]:
# %load_ext rpy2.ipython

In [ ]:
# %%R
# Your R code here

In [ ]:
# !pip install rpy2

In [ ]:
# Load the R extension
# %reload_ext rpy2.ipython

In [ ]:
# Matrix Structure - m rows, n columns, mn entries having unique position
A <- matrix(data = c(-3,2,893,0.17),nrow = 2, ncol = 2)
A

[,1] [,2]  
[1,] -3   893.00
[2,]  2     0.17

In [ ]:
# Matrix Structure - data is arranged in column manner by default, without suplying nrow and ncol R returns a column matrix, arrangement of data could be controlled by "byrow" argument
mat_col = matrix(data = c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = FALSE)
mat_col

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [ ]:
mat_row = matrix(data = c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = TRUE)
mat_row

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
# Multiple vectors could be arranged in array, rbind, cbind
rbind(1:3,4:6)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
cbind(c(1,4),c(2,5),c(3,6))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
# "dim" gives the dimension of a matrix
mymat <- rbind(c(1,3,4),5:3, c(100,20,90), 11:13)
mymat

[,1] [,2] [,3]
[1,]   1   3    4  
[2,]   5   4    3  
[3,] 100  20   90  
[4,]  11  12   13

In [ ]:
print(dim(mymat))
print(nrow(mymat))
print(ncol(mymat))
print(dim(mymat)[2])

[1] 4 3
[1] 4
[1] 3
[1] 3


###**Extracting Elements from a matrix**

In [ ]:
A <- matrix(c(0.3,4.5,55.3,91,0.1,105.5,-4.2,8.2,27.9), nrow = 3, ncol = 3)
A

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

In [ ]:
diag(x = A)

[1]  0.3  0.1 27.9

In [ ]:
A[3,2]

[1] 105.5

In [ ]:
A[,2]

[1]  91.0   0.1 105.5

In [ ]:
A[2:3,]

[,1] [,2]  [,3]
[1,]  4.5   0.1  8.2
[2,] 55.3 105.5 27.9

In [ ]:
A[,c(3,1)]

[,1] [,2]
[1,] -4.2  0.3
[2,]  8.2  4.5
[3,] 27.9 55.3

In [ ]:
A[c(3,1),2:3]

[,1]  [,2]
[1,] 105.5 27.9
[2,]  91.0 -4.2

###**Manipulating Matrix**

In [ ]:
A

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

In [ ]:
A[,-2]

[,1] [,2]
[1,]  0.3 -4.2
[2,]  4.5  8.2
[3,] 55.3 27.9

In [ ]:
A[-1,3:2]

[,1] [,2] 
[1,]  8.2   0.1
[2,] 27.9 105.5

In [ ]:
A[-1,-2]

[,1] [,2]
[1,]  4.5  8.2
[2,] 55.3 27.9

In [ ]:
A[-1,-c(2,3)]

[1]  4.5 55.3

In [ ]:
B <- A
B

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

In [ ]:
B[2,] <- 1:3
B

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  1.0   2.0  3.0
[3,] 55.3 105.5 27.9

In [ ]:
B[c(1,3),2] <- 900
B

[,1] [,2] [,3]
[1,]  0.3 900  -4.2
[2,]  1.0   2   3.0
[3,] 55.3 900  27.9

In [ ]:
B[,3] <- B[3,]

In [ ]:
A

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

In [ ]:
B[c(1,3),2:1] <- c(65,-65,88,-88)
B

[,1] [,2] [,3] 
[1,]  88   65   55.3
[2,]   1    2  900.0
[3,] -88  -65   27.9

In [ ]:
B[c(1,3),c(1,3)] <- c(-7,7)
B

[,1] [,2] [,3]
[1,] -7    65   -7 
[2,]  1     2  900 
[3,]  7   -65    7

In [ ]:
diag(x = B) <- rep(x = 0, times = 3)
B

[,1] [,2] [,3]
[1,] 0     65   -7 
[2,] 1      0  900 
[3,] 7    -65    0